(function (global) {
  const areaCatalog = [
  {
    "id": "almacen-de-concentrado-y-operaciones-portuarias",
    "title": "Almacén de Concentrado y Operaciones Portuarias",
    "icon": "🏢",
    "summary": "Área de Almacén de Concentrado y Operaciones Portuarias",
    "accent": "#3B82F6",
    "color": "#3B82F6",
    "departmentTitle": "Gerencia de Almacén de Concentrado y Operaciones Portuarias",
    "description": "Coordinar, administrar y ejecutar los trabajos referentes a las operaciones de recepción, descarga, almacenamiento y despachos de concentrado en almacén Chinalco en Callao, monitoreando y validando las operaciones de embarque a granel por Transportadora Callao a fin de asegurar la ejecución del plan de ventas mensual, monitoreando el cumplimiento de procedimientos de gestión y operativos en Callao.",
    "npc": "Gerente",
    "npcRole": "Responsable de Almacén de Concentrado y Operaciones Portuarias",
    "quote": "Bienvenido al área de Almacén de Concentrado y Operaciones Portuarias",
    "competencies": [],
    "mapLabel": "Almacén",
    "positions": [
      {
        "title": "COORDINADOR SR DE ALMACEN Y OPERACIONES PORTUARIAS",
        "category": "Analista",
        "level": "Nivel 6",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "6",
        "experience_position": "4",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN\nINGENIERÍA METALURGICA\nINGENIERÍA QUIMICA\nQUÍMICA\nINGENIERÍA MARÍTIMA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Coordinar y dar soporte en la planificación de las operaciones de recepción, almacenaje, toma de muestras, mezcla y homogenización de los concentrados de Cu en el almacén de Impala y su posterior embarque vía Transportadora Callao o despachos en camiones o en contenedores",
          "Revisar el plano de estiba, la secuencia de carga (proporcionada por el capitán de la nave), considerando el nivel de stock en los almacenes de M.C.P y proponiendo mejoras para un mejor desarrollo de las actividades relacionadas.",
          "Coordinar la ejecución de los procedimientos de gestión y operativos tanto de MCP como de los contratistas, participando en las reuniones de coordinación del programa de embarques / despachos y recepción de vagones en Callao.",
          "Dar seguimiento a los principales KPIs de la Operación, MCP Callao, Agente Marítimo, generando los reportes de embarque/ estado naves , los documentos post embarque, productividad de descarga de vagones.",
          "Controlar el inventario y el patrimonio del almacén de concentrado en Callao, realizando conteos programados y manteniéndolo en buenas condiciones de estado y conservación.",
          "Controlar la limpieza de las fajas , tolvas de transferencia, verificando el proceso de recuperación ,asi como la limpieza del volteador de vagones y disposición de remanentes.",
          "Controlar y dar seguimiento a la asignación de vagones en función a la calidad y capacidad de almacenamiento en Callao, controlando la eficiencia de descarga de vagones.",
          "Dar seguimiento al cumplimiento de requerimiento de seguridad de parte de todos los proveedores.",
          "Controlar y verificar el cumplimiento de normas de calidad ISO en la toma, determinación de humedad y preparación de muestras",
          "Registrar y verificar los datos requeridos del proceso logístico de concentrado en el sistema de gestión de información del área (WAPSA).",
          "Controlar el cumplimiento de los requisitos establecidos por la certificación OEA, dentro de la ejecución de los procesos del área.",
          "12 Cubrir las operaciones de supervisión de despacho de concentrado desde Mina en ausencia del Supervisor de Almacén de Concentrado Mina."
        ]
      },
      {
        "title": "COORDINADOR SR DE CONTROL DE CALIDAD",
        "category": "Analista",
        "level": "Nivel 6",
        "blurb": "INGENIERÍA METALURGICA",
        "speciality": "INGENIERÍA METALURGICA",
        "experience_general": "6",
        "experience_position": "4",
        "experience_sector": "3",
        "carrera_afin": "INGENIERÍA ESTADISTICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA QUIMICA\nQUÍMICA\nINGENIERÍA MARÍTIMA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Planificar y coordinar las actividades de toma de muestra en Mina y Callao tanto para recepción como para despachos de concentrados de mineral.",
          "Planificar, desarrollar y coordinar una serie pruebas para saber el comportamiento del concentrado de cobre (preparación de la muestra patrón, la realización del round robin test)",
          "Monitorear el Sistema Wapsa, variación de As, humedades, stock y tomar las medidas correctoras y preventivas pertinentes.",
          "Controlar el cumplimiento de los planes de verificación, calibración, certificación y mantenimiento de los equipos de pesaje, determinación de humedad en Mina, Callao(almacén y Puerto) y otros almacenes donde MCP tenga operaciones.",
          "Revisar el reporte de pesos, leyes y humedades en Mina/ Callao y resultados de análisis de blending en Callao tanto para recepción como para despacho proporcionado por SGS - Cotecna - Impala - Supervisor Cliente.",
          "Controlar el método de ensayo de los laboratorios, muestreo, determinación de humedad y análisis químico en Mina/ Callao.",
          "Monitorear la gestión de laboratorios que brindan servicio al área realizando visita in situ y auditorias de campo, proponiendo acciones de mejora y gestionando los servicios de calidad de Mina y Callao (logística comercial).",
          "Ejecutar procedimientos de muestrero sampling y pesaje evaluando su actualización según la necesidad del área.",
          "Integrar la información de WSMD para mejorar los controles de QA/QC.",
          "Controlar proyectos que optimizan los procesos de muestreo y ensayo en Callao / Mina."
        ]
      },
      {
        "title": "JEFE DE ALMACEN DE CONCENTRADO Y OPERACIONES PORTUARIAS",
        "category": "Jefe",
        "level": "Nivel 10",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "10",
        "experience_position": "8",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN DE EMPRESAS\nINGENIERÍA QUIMICA\nINGENIERÍA METALURGICA\nQUÍMICA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Planificar, supervisar y controlar las operaciones de recepción, almacenaje, toma de muestras, mezcla y homogenización de los concentrados de Cu en el almacén de Impala y su posterior embarque vía Transportadora Callao y/o despachos en camiones o en contenedores.",
          "Controlar las operaciones de mezcla de concentrado, priorizando la maximización del concentrado CIQ",
          "Cubrir las operaciones de supervisión de despacho de concentrado desde Mina en ausencia del Supervisor de Almacén de Concentrado Mina.",
          "Controlar y verificar los costos asociados a la logística comercial ($/TMH) cumpliendo el presupuesto anual.",
          "Revisar y validar el valor de TML y humedad del concentrado, el plano de estiba, la secuencia de carga (proporcionada por el capitán de la nave), considerando el nivel de stock en los almacenes de MCP y proponiendo mejoras para un mejor desarrollo de las actividades relacionadas.",
          "Monitorear y dar seguimiento a ejecución de los procedimientos de gestión y operativos tanto de MCP como de los contratistas, liderando las reuniones de coordinación del programa de embarques / despachos.",
          "Monitorear los principales KPIs de la Operación logística de concentrado MCP Callao, Agente Marítimo, revisando los reportes de embarque/ estado naves y los documentos generados post embarque",
          "Gestionar el inventario y el patrimonio del almacén de concentrado en Callao, evaluando los conteos programados y condiciones de estado/ conservación.",
          "Controlar y validar la asignación de vagones en función a la calidad y capacidad de almacenamiento en Callao, controlando la eficiencia de descarga de vagones.",
          "Formular, fomentar, planificar e implementar nuevos proyectos de trazabilidad y control integrado de logística de concentrados, optimizando los procesos del área.",
          "Controlar el cumplimiento de los requisitos establecidos por la certificación OEA, dentro de la ejecución de los procesos del área."
        ]
      },
      {
        "title": "SUPERINTENDENTE DE ALMACEN DE CONCENTRADO Y OPERACIONES PORTUARIAS",
        "category": "Superintendente",
        "level": "Nivel 15",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "15",
        "experience_position": "8",
        "experience_sector": "5",
        "carrera_afin": "INGENIERÍA METALURGICA\nINGENIERÍA QUIMICA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Planificar, dirigir, controlar y supervisar las operaciones de carguío, despacho  e inventario de concentrados de cobre desde planta (almacén domo) hasta la recepción, almacenamiento y despacho de concentrados de cobre en Callao, mediante una atención de manera eficiente,",
          "Planificar, controlar y supervisar el proceso de control y aseguramiento de calidad para el concentrado de cobre en toda la cadena logística desde la toma de muestra, pesajes, determinación de humedad, análisis químicos, pruebas de validación, planes de calibración y mantenimientos, etc.",
          "Coordinar y controlar la asignación de las rumas acorde a las calidades producidas versus la capacidad de almacenamiento en Callao.",
          "Planear, dirigir, coordinar,  controlar y supervisar las operaciones de homogenización y mezclas en el almacén en Callao, así como la maximización de espacios.",
          "Planear, dirigir, coordinar y controlar el embarque y/o despachos de concentrados de cobre que requiere la operación minera, en sus diferentes modalidades ( traslado externo, contenedores, entregas directas y embarque a granel) realizado por los distintos operadores logísticos y marítimos, según el plan de entregas del mes.",
          "Planear, coordinar, desarrollar y supervisar los proyectos de mejora (CAPEX - OPEX) asociado a la logística comercial tanto para el mantenimiento de las operaciones como para su expansión.",
          "Negociar con principales proveedores de servicio asociados a la cadena logística comercial.",
          "Seguimiento a las operaciones y prioridades estratégicas para el logro del cumplimiento de los objetivos, coordinando con las áreas de mina, producción, compras y contratos, transportes,  comercial entre otros.",
          "Desarrollo de nuevos negocios, herramientas y/o aplicaciones.",
          "Planear, programar, participar y desarrollar reuniones con los miembros del equipo de la logística comercial así como con otras áreas dentro de la organización.",
          "Controlar y supervisar el cumplimiento de los Procedimientos internos y externos asociados a la logística comercial.",
          "12 Resolver conflictos y/o bloqueos que afecten a la operación, además de atender y desarrollar reportes solicitados por la Gerencia y alta dirección"
        ]
      },
      {
        "title": "SUPERVISOR DE ALMACEN DE CONCENTRADO MINA",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "INGENIERÍA METALURGICA",
        "speciality": "INGENIERÍA METALURGICA",
        "experience_general": "8",
        "experience_position": "5",
        "experience_sector": "3",
        "carrera_afin": "INGENIERÍA INDUSTRIAL\nINGENIERÍA QUIMICA\nQUÍMICA\nINGENIERÍA MARÍTIMA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Coordinar, controlar y supervisar los procesos de recepción y despacho de concentrado en el almacén de concentrados en mina",
          "Verificar y dar conformidad a la documentación logística del almacén de concentrados en mina (guías de recepción / despacho, vales de salida, devoluciones y otras)",
          "Controlar adecuadamente el inventario, en calidad y cantidad.",
          "Elaborar y presentar el reporte de los movimientos del almacén de concentrados en mina hacia Callao, así como KPI clave.",
          "Coordinar con la Jefatura de Transporte de Concentrados el programa de abastecimiento de vagones y asegurar su cumplimiento",
          "Verificar el cumplimiento de la norma de calidad ISO 12743 / ISO 10251 para la toma de muestra de concentrado y determinación de humedad del concentrado de cobre. Asegura el cumplimiento de Normas Internacionales de Calidad y procedimientos MCP.",
          "Ingresar la información de despacho, pesos, guías así como control de humedades y leyes en el sistema comercial WAPSA",
          "Validar la información del WAPSA-modulo Mina",
          "Coordina con las distintas áreas internas para el desarrollo de proyectos de mejora Velar el cumplimiento del presupuesto anual (CAPEX/OPEX)"
        ]
      }
    ],
    "functions": [],
    "x": 100,
    "y": 100
  },
  {
    "id": "almacenes-y-control-de-inventario",
    "title": "Almacenes y Control de Inventario",
    "icon": "🏢",
    "summary": "Área de Almacenes y Control de Inventario",
    "accent": "#8B5CF6",
    "color": "#8B5CF6",
    "departmentTitle": "Gerencia de Almacenes y Control de Inventario",
    "description": "Coordinar, administrar y ejecutar los trabajos referentes al control y reporte de las operaciones de descarga, recibo, almacenaje y despacho en los almacenes de la U.M. Toromocho, dando conformidad a las guías de materiales explosivos e insumos químicos y monitoreando el uso correo de equipos durante las actividades del almacén a fin de contribuir con el abastecimiento de materiales requeridos por las diferentes áreas de la empresa, haciendo uso eficiente de los equipos del almacén.",
    "npc": "Gerente",
    "npcRole": "Responsable de Almacenes y Control de Inventario",
    "quote": "Bienvenido al área de Almacenes y Control de Inventario",
    "competencies": [],
    "mapLabel": "Almacenes",
    "positions": [
      {
        "title": "COORDINADOR SR DE ALMACEN",
        "category": "Analista",
        "level": "Nivel 6",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "6",
        "experience_position": "4",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN\nCONTABILIDAD\nINGENIERÍA MECANICA\nINGENIERÍA QUIMICA\nINGENIERÍA ESTADISTICA\nESTADÍSTICA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Verificar, controlar y dar conformidad a las guías de materiales explosivos e insumos químicos",
          "Monitorear y coordinar las labores de descarga, recibo, almacenamiento y despacho de materiales en el Almacén, gestionando las comunicaciones de entrega de materiales solicitados con clientes internos y externos.",
          "Controlar y verificar la cantidad, calidad de los materiales entregados por los proveedores y transportistas",
          "Monitorear y coordinar el uso de equipos para las actividades propias del almacén como el chequeo, almacenamiento y despacho (camión, grúas y montacargas)",
          "Controlar e ingresar en el sistema (ERP) la información de recepción y despacho de materiales, verificando el inventario físico en comparación con lo registrado en el sistema.",
          "Monitorear y coordinar el conteo cíclico e inventarios programados por control interno, en los diferentes almacenes de la U.M. Toromocho.",
          "Controlar las operaciones del almacén de acuerdo a lo establecido en las políticas, procedimientos, estándares e indicadores logísticos del almacén."
        ]
      },
      {
        "title": "COORDINADOR SR DE GESTION DE INVENTARIO",
        "category": "Analista",
        "level": "Nivel 6",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "6",
        "experience_position": "2",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN\nCONTABILIDAD\nESTADÍSTICA\nINGENIERIAS AFINES",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Organizar, elaborar y monitorear los conteos diarios y reconteos semanales en todos los almacenes.",
          "Coordinar la toma de inventarios anual.",
          "Verificar, controlar y reportar los cargos directos, los obsoletos y los ítems vencidos.",
          "Evaluar, proponer y generar propuestas de mejora de los espacios de almacenamiento con layouts y otras herramientas.",
          "Verificar, controlar y reportar los materiales en calidad de Surplus del TEP.",
          "Verificar, controlar y reportar los Backlogs."
        ]
      },
      {
        "title": "JEFE DE ALMACENES",
        "category": "Jefe",
        "level": "Nivel 10",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "10",
        "experience_position": "5",
        "experience_sector": "5",
        "carrera_afin": "INGENIERÍA ESTADISTICA\nINGENIERÍA MECANICA\nINGENIERÍA QUIMICA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Liderar las guardias y controlar el cumplimiento del plan de trabajo asignado, coordinando con los supervisores y coordinadores de almacenes todas las actividades que se realizaran en el turno correspondiente",
          "Planificar y monitorear las operaciones logisticas referidas a los procesos de descarga, recepción, almacenamiento y despacho de materiales en los diferentes almacenes de la U.M. Toromocho, dirigiendo acciones ante alguna disconformidad en la recepción de materiales, insumos o equipos.",
          "Controlar y dar conformidad a las guías de materiales explosivos e insumos químicos.",
          "Verificar la relación entre los materiales y equipos despachados o recepcionados, con sus respectivas ordenes de compra o despacho, controlando el movimiento de materiales en los almacenes de la U.M. Toromocho.",
          "Controlar el uso de equipos (camión, grúas y montacargas) dentro de las actividades de recepción, almacenamiento y despacho en los almacenes de la U.M. Toromocho.",
          "Participar en la elaboración de KPIs y presupuesto (CAPEX y OPEX) del área en coordinación con el Superintendente de Almacenes y control de inventario, monitoreando su cumplimiento.",
          "Controlar los registros de entrada y salida de materiales, monitoreando los registros de ingreso de materiales en el ERP.",
          "Gestionar los contratos del área controlando el nivel del servicio y soporte acordado así como la disponibilidad de recursos necesarios",
          "Dirigir a los miembros de su equipo, siendo responsable del cumplimiento de estándares y objetivos de evaluación / desarrollo / capacitación del personal."
        ]
      },
      {
        "title": "SUPERINTENDENTE DE ALMACENES Y CONTROL DE INV.",
        "category": "Superintendente",
        "level": "Nivel 15",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "15",
        "experience_position": "8",
        "experience_sector": "5",
        "carrera_afin": "INGENIERÍA ELECTRICA\nINGENIERÍA MECANICA\nINGENIERÍA DE SISTEMAS\nINGENIERIAS AFINES\nCONTABILIDAD",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Dirigir los procesos de almacenamiento (mina y planta) de la U.M. Toromocho, controlando las actividades de descarga, recibo, almacenamiento y despacho de materiales en coordinación con la Jefatura de Almacenes.",
          "Formular la estrategia y plan de control de inventarios de los almacenes (mina y planta) de la U.M. Toromocho, monitoreando suministro de los principales insumos críticos para la operación.",
          "Planificar las acciones preventivas y correctivas para las posibles contingencias (desabastecimiento y rotura de stock) en los procesos de almacenes.",
          "Planificar y establecer los criterios para la realización de los conteos cíclicos e inventarios programados en los diferentes almacenes de la U.M. Toromocho.",
          "Definir y difundir las políticas, prácticas y normas del funcionamiento de los almacenes de la U.M. Toromocho.",
          "Elaborar el presupuesto de las áreas a cargo para reportar a la gerencia."
        ]
      },
      {
        "title": "SUPERVISOR DE ALMACENES",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "8",
        "experience_position": "5",
        "experience_sector": "3",
        "carrera_afin": "INGENIERÍA MECANICA\nINGENIERÍA QUIMICA\nINGENIERÍA ESTADISTICA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Supervisar el cumplimiento del plan de trabajo asignado, coordinando con los almaceneros todas las actividades que se realizaran en el turno correspondiente.",
          "Supervisar y controlar los procesos de descarga, recepción, almacenamiento y despacho de materiales en los almacenes de la U.M. Toromocho (mina y planta), validando la documentación logística (guías de recepción / despacho, vales de salida, devoluciones y otras) de las instalaciones a cargo.",
          "Revisar y validar la información contenida en las guías de materiales explosivos e insumos químicos.",
          "Coordinar el conteo físico del listado del conteo cíclico e inventarios programados en los almacenes de la U.M. Toromocho (mina y planta).",
          "Monitorear el estado físico de las instalaciones de los almacenes de la U.M. Toromocho, manteniendo el orden, limpieza y condiciones de almacenamiento de las instalaciones bajo su cargo.",
          "Supervisar el proceso de movimientos de materiales en los diferentes almacenes de la U.M. Toromocho (mina y planta), validando todas las transacciones de salida y entrada de materiales registrada en el sistema (ERP) y presentando los reportes requeridos de las instalaciones a cargo."
        ]
      }
    ],
    "functions": [],
    "x": 180,
    "y": 160
  },
  {
    "id": "comercial",
    "title": "Comercial",
    "icon": "💼",
    "summary": "Área de Comercial",
    "accent": "#EC4899",
    "color": "#EC4899",
    "departmentTitle": "Gerencia de Comercial",
    "description": "Supervisar, controlar y coordinar las acciones referentes a la  ejecución de los contratos de venta a fin de asegurar el cumplimiento de las condiciones establecidas, de acuerdo a estándares de la empresa.",
    "npc": "Gerente",
    "npcRole": "Responsable de Comercial",
    "quote": "Bienvenido al área de Comercial",
    "competencies": [],
    "mapLabel": "Comercial",
    "positions": [
      {
        "title": "ADMINISTRADOR DE CONTRATOS COMERCIALES SR",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "8",
        "experience_position": "5",
        "experience_sector": "3",
        "carrera_afin": "INGENIERÍA INDUSTRIAL",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Administrar los contratos de venta de concentrados Cu, supervisando y coordinando las acciones requeridas durante su ejecución.",
          "Revisar los reportes de producción y la disponibilidad de los productos a comercializar, evaluando las acciones requeridas para la atención de ventas planificadas.",
          "Administrar el registro de información de contratos, cuotas y modificaciones en el sistema comercial (Trader) y otros reportes requeridos.",
          "Realizar las instrucciones de embarque, coordinando la determinación de los pesos y leyes finales con los clientes.",
          "Elaborar los documentos de embarque: BL, Factura, Certificado de Origen, Certificado de Peso y Calidad, entre otros"
        ]
      },
      {
        "title": "ANALISTA WSMD",
        "category": "Asistente",
        "level": "Nivel 3",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "3",
        "experience_position": "2",
        "experience_sector": "2",
        "carrera_afin": "ADMINISTRACIÓN\nESTADISTICA E INFORMATICA\nMETALURGIA\nINGENIERÍA QUIMICA",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Dar soporte en la formulación de propuestas de canje de leyes y/o dirimencia por cada entrega para revisión de los administradores de contratos",
          "Elaborar las cartas de reclamo a los laboratorios según corresponda, dando seguimiento a las coordinaciones requeridas hasta la respuesta final.",
          "Analizar y desarrollar el perfil de canje por cada cliente, implementando trazabilidad estadistica de canjes de leyes.",
          "Analizar y dar soporte en el control de diferencias de pesos en origen y destino. Contrinuir con el control de pesos en origen y destino.",
          "Participar en la negociación de las tarifas de los laboratorios y preparar el presupuesto de canje de leyes y supervisión.",
          "Elaborar información estadística respecto a los procesos de canje y pesos."
        ]
      },
      {
        "title": "COORDINADOR SR DE COMERCIAL",
        "category": "Analista",
        "level": "Nivel 6",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "6",
        "experience_position": "4",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN\nECONOMÍA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Ejecutar el análisis económico previo a las ventas de concentrado de cobre y evaluación costo-beneficio del área comercial (ventas, mezcla de calidades, tiempos de entrega, etc.), brindando información para la toma de decisiones",
          "Elaborar y emitir facturas y notas de ajuste por concepto de venta de concentrado de cobre, utilizando el sistema SAP.",
          "Revisar las liquidaciones de venta y los documentos de soporte, notificando la validez de las facturas y notas de ajuste de ventas de concentrado de cobre.",
          "Coordinar y atender los requisitos de auditorias externas e Internas relacionadas a la venta de concentrado de cobre.",
          "Elaborar reportes solicitados las diferentes áreas de MCP y alta gerencia, incluyendo los reportes contables de venta de cierre contable y tributario requeridos por el área de contabilidad.",
          "Registrar la información de ventas en la Declaración Estadística Mensual (ESTAMIN) y Declaración Anual Consolidada (DAC).",
          "Actualizar la información de archivos de gestión de ventas del área comercial (inventarios, status de entregas y contratos, disponibilidad de concentrados para la venta, etc.), proporcionando información para la generación de estrategias comerciales a aplicar.",
          "Administrar la informacion y documentación de soporte de las ventas, clientes y proveedores del área comercial ventas.",
          "Dar soporte a todas las actividades relacionadas con la administración de los contratos de venta."
        ]
      },
      {
        "title": "COORDINADOR SR DE EXPORTACIONES",
        "category": "Analista",
        "level": "Nivel 6",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "6",
        "experience_position": "4",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓ DE TURISMO Y DE NEGOCIOS INTERNACIONALES\nINGENIERÍA INDUSTRIAL\nCOMERCIO INTERNACIONAL\nCOMERCIO EXTERIOR\nLOGISTICA Y COMERCIAL\nMARKETING",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Dar soporte al Supervisor de Exportaciones en los procesos de licitación y cierre los embarques de concentrado en contenedores y a granel según requerimientos definidos por el área de Comercial Ventas y el Cliente, alineados a las políticas y procedimientos de MCP",
          "Administrar los embarques asignados por el Supervisor de Exportaciones, realizando seguimiento al cumplimiento de las condiciones comerciales y contractuales acordadas para los embarques.",
          "Coordinar con el área de Logística Comercial, Brokers, Operadores, Armadores, Líneas Navieras, área de Comercial Ventas, Agentes Marítimos, Empresas de Supervisión y Agente de Aduanas las operaciones de cada embarque y la emisión de documentación relacionada a estos embarques",
          "Elaborar y/o revisar documentos contractuales y otros requeridos para los embarques, gestionando la firma de todos ellos con las partes correspondientes.",
          "Gestionar la solicitud de documentación para la numeración y el refrendo de las DAMs, gestionando la regularización de las DAMs en coordinación con el Agente de Aduanas.",
          "Realizar el archivamiento físico y digital de toda la documentación relacionada a todos los embarques, manteniendo actualizado los files según formatos utilizados.",
          "Generar reportes y presentaciones de gestión y mercado para clientes externos e internos de la organización, desarrollando relaciones con los clientes a través de la comunicación continua y servicio oportuno según sea requerido",
          "Apoyar al Supervisor de Exportaciones en el desarrollo de campañas de regularización de documentación de embarques, proyectos internos y análisis requeridos por la Jefatura Comercial, Gerencia Comercial, Vicepresidencia Comercial y Gerencia General."
        ]
      },
      {
        "title": "SUPERINTENDENTE COMERCIAL",
        "category": "Superintendente",
        "level": "Nivel 15",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "15",
        "experience_position": "10",
        "experience_sector": "5",
        "carrera_afin": "ADMINISTRACIÓN\nECONOMÍA\nINGENIERÍA METALURGICA",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Evaluar y realizar seguimiento permanente a los mercados de concentrado de cobre.",
          "Evaluar las propuestas comerciales y negociación de términos y condiciones en el mercado spot, tomando en cuenta todos los aspectos del proceso y la estrategia comercial.",
          "Dirigir y supervisar el desarrollo de los planes mensuales de venta de los distintos productos y subproductos de la empresa.",
          "Realizar el planeamiento del programa de embarques para los productos y subproductos de la empresa.",
          "Supervisar las negociaciones y evaluaciones de contratos de fletes marítimos para los productos y subproductos de la empresa.",
          "Supervisar la gestión de coberturas de cobre y plata (negociación de contratos ISDA con fondos financieros o bancos, elaboración de presentaciones mensuales al Comite de Hedge, aprobación formal de las fijaciones, ejecución de fijaciones, emisión de reportes con valorizaciones).",
          "Administrar y controlar los \"libros\" de período de cotización de la operaciones de venta de concentrado de cobre y plata.",
          "Reportar periódicamente los resultados de ventas y costos de venta versus presupuesto.",
          "Supervisar los procesos de liquidación, facturación y reporte de ventas asi como el requerimiento de información de ventas del área de finanzas y Casa Matriz.",
          "Supervisar el WMSD (control de pesos y leyes)"
        ]
      },
      {
        "title": "SUPERVISOR DE COBERTURAS Y MERCADOS",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "ECONOMÍA",
        "speciality": "ECONOMÍA",
        "experience_general": "8",
        "experience_position": "3",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Administrar y evaluar la identificación de estrategias y oportunidades de mejora para las operaciones de coberturas.",
          "Administrar las políticas, procedimientos y buenas practicas de coberturas, actualizándolos según sea requerido.",
          "Administrar y evaluar la identificación de riesgos de ejecución, autorizaciones y tributarios respecto a las transacciones de cobertura realizadas.",
          "Revisar la coherencia entre las ventas físicas y las operaciones de coberturas.",
          "Coordinar con los bancos y otras entidades financieras la posición diaria de las coberturas.",
          "Presentar reportes a la presidencia y al comité de coberturas.",
          "Preparar informes de análisis de mercado demanda/oferta y precio de concentrados y metales"
        ]
      },
      {
        "title": "SUPERVISOR DE EXPORTACIONES",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "8",
        "experience_position": "5",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES\nINGENIERÍA INDUSTRIAL\nCOMERCIO INTERNACIONAL\nCOMERCIO EXTERIOR\nINGENIERÍA COMERCIAL\nLOGISTICA Y COMERCIAL\nMARKETING",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Licitar, cerrar y supervisar cada embarque concentrado (contenedores y a granel) y asegurar el cumplimiento de lo acordado con los clientes",
          "Administrar los contratos de fletamento (Charter Party) incluyendo el establecimiento de los cálculos de tiempo y posibles reclamos de los clientes y/o armadores",
          "Coordinar con puerto las operaciones y la emisión de documentación de embarque",
          "Validar los reportes del mercado naviero, estimaciones de tarifas de fletes, e informes de tarifas de fletes reales para cada posición contratada vs. tarifa real alcanzada (performance).",
          "Revisar la información de los reportes generados del proceso de exportación (embarques) en el sistema comercial."
        ]
      }
    ],
    "functions": [],
    "x": 260,
    "y": 220
  },
  {
    "id": "compras-y-contratos",
    "title": "Compras y Contratos",
    "icon": "📋",
    "summary": "Área de Compras y Contratos",
    "accent": "#F59E0B",
    "color": "#F59E0B",
    "departmentTitle": "Gerencia de Compras y Contratos",
    "description": "Coordinar, controlar y ejecutar la adquisición oportuna de servicios requeridos por todas las áreas usuarias, de acuerdo al Plan Anual de Contrataciones; optimizando los costos y uso de recursos, asegurando disponibilidad y calidad.",
    "npc": "Gerente",
    "npcRole": "Responsable de Compras y Contratos",
    "quote": "Bienvenido al área de Compras y Contratos",
    "competencies": [],
    "mapLabel": "Compras",
    "positions": [
      {
        "title": "ADMINISTRADOR DE CONTRATOS 1 - OPERACIONES",
        "category": "Analista",
        "level": "Nivel 5",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "5",
        "experience_position": "3",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN DE EMPRESAS\nDERECHO\nINGENIERÍA CIVIL\nINGENIERÍA DE MINAS\nINGENIERÍA DE SISTEMAS\nINGENIERÍA ELECTRONICA\nINGENIERÍA EMPRESARIAL\nINGENIERÍA ESTADISTICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Revisar y mantener actualizada la información del plan de contratación de servicios reportando las desviaciones que ponen en riesgo el cumplimiento de las actividades planeadas.",
          "Gestionar los requerimientos (SOLPEDS) de Mediana y Alta Complejidad liderando los procesos de contratación por montos entre US$ 500,000 y US$ 1MM",
          "Gestionar las etapas del concurso (aprobación de postores, visita a terreno, absolución de consultas, evaluación, adjudicación, etc) y coordinar con el usuario solicitante la elección final del proveedor y negociación de los mejores términos y condiciones.",
          "Revisar los documentos recibidos del usuario (SOW, especificaciones técnicas, presupuesto base, etc)",
          "Realizar la evaluación de las propuestas económicas y condiciones de entrega en coordinación con el área solicitante.",
          "Elaborar el cronograma de concurso, lista de postores y documentos de concurso (bases, cartas de invitación, etc) en coordinación con el usuario solicitante.",
          "Gestionar la administración contractual y aprobación de valorizaciones, reclamos, penalidades, correspondencia contractual y reportar las contrataciones frecuentes que pueden ser negociadas mediante Acuerdo de Precios, Consignación u otros con proveedores, así como el respectivo cierre de contrato.",
          "Preparar, consolidar y custodiar la documentación de adjudicación y contractual, coordinando con el proveedor seleccionado lo necesario para la admisión del personal del proveedor a las instalaciones de MCP.",
          "Realizar evaluaciones periódicas del desempeño de los proveedores en coordinación con el jefe directo.",
          "Identificar oportunamente los riegos de incumplimiento y cambios sobre las condiciones iniciales de los contratos."
        ]
      },
      {
        "title": "ADMINISTRADOR DE CONTRATOS 2 - OPERACIONES",
        "category": "Asistente",
        "level": "Nivel 3",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "3",
        "experience_position": "2",
        "experience_sector": "2",
        "carrera_afin": "ADMINISTRACIÓN DE EMPRESAS\nDERECHO\nINGENIERÍA CIVIL\nINGENIERÍA DE MINAS\nINGENIERÍA DE SISTEMAS\nINGENIERÍA ELECTRONICA\nINGENIERÍA EMPRESARIAL\nINGENIERÍA ESTADISTICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Revisar y mantener actualizada la información del plan de contratación de servicios reportando las desviaciones que ponen en riesgo el cumplimiento de las actividades planeadas.",
          "Gestionar los requerimientos (SOLPEDS) de Baja y Mediana Complejidad liderando los procesos de contratación por montos hasta US$ 500,000",
          "Gestionar las etapas del concurso (aprobación de postores, visita a terreno, absolución de consultas, evaluación, adjudicación, etc) y coordinar con el usuario solicitante la elección final del proveedor y negociación de los mejores términos y condiciones.",
          "Revisar los documentos recibidos del usuario (SOW, especificaciones técnicas, presupuesto base, etc)",
          "Realizar la evaluación de las propuestas económicas y condiciones de entrega en coordinación con el área solicitante.",
          "Elaborar el cronograma de concurso, lista de postores y documentos de concurso (bases, cartas de invitación, etc) en coordinación con el usuario solicitante.",
          "Gestionar la administración contractual y aprobación de valorizaciones, reclamos, penalidades, correspondencia contractual y reportar las contrataciones frecuentes que pueden ser negociadas mediante Acuerdo de Precios, Consignación u otros con proveedores, así como el respectivo cierre de contrato.",
          "Preparar, consolidar y custodiar la documentación de adjudicación y contractual, coordinando con el proveedor seleccionado lo necesario para la admisión del personal del proveedor a las instalaciones de MCP.",
          "Realizar evaluaciones periódicas del desempeño de los proveedores en coordinación con el jefe directo.",
          "Identificar oportunamente los riegos de incumplimiento y cambios sobre las condiciones iniciales de los contratos."
        ]
      },
      {
        "title": "ADMINISTRADOR DE CONTRATOS 2 - PROYECTOS",
        "category": "Asistente",
        "level": "Nivel 3",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "3",
        "experience_position": "2",
        "experience_sector": "2",
        "carrera_afin": "ADMINISTRACIÓN DE EMPRESAS\nDERECHO\nINGENIERÍA CIVIL\nINGENIERÍA DE MINAS\nINGENIERÍA DE SISTEMAS\nINGENIERÍA ELECTRONICA\nINGENIERÍA EMPRESARIAL\nINGENIERÍA ESTADISTICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Revisar y mantener actualizada la información del plan de contratación de servicios reportando las desviaciones que ponen en riesgo el cumplimiento de las actividades planeadas.",
          "Gestionar los requerimientos (SOLPEDS) de Baja y Mediana Complejidad liderando los procesos de contratación por montos hasta US$ 500,000",
          "Gestionar las etapas del concurso (aprobación de postores, visita a terreno, absolución de consultas, evaluación, adjudicación, etc) y coordinar con el usuario solicitante la elección final del proveedor y negociación de los mejores términos y condiciones.",
          "Revisar los documentos recibidos del usuario (SOW, especificaciones técnicas, presupuesto base, etc)",
          "Realizar la evaluación de las propuestas económicas y condiciones de entrega en coordinación con el área solicitante.",
          "Elaborar el cronograma de concurso, lista de postores y documentos de concurso (bases, cartas de invitación, etc) en coordinación con el usuario solicitante.",
          "Gestionar la administración contractual y aprobación de valorizaciones, reclamos, penalidades, correspondencia contractual y reportar las contrataciones frecuentes que pueden ser negociadas mediante Acuerdo de Precios, Consignación u otros con proveedores, así como el respectivo cierre de contrato.",
          "Preparar, consolidar y custodiar la documentación de adjudicación y contractual, coordinando con el proveedor seleccionado lo necesario para la admisión del personal del proveedor a las instalaciones de MCP.",
          "Realizar evaluaciones periódicas del desempeño de los proveedores en coordinación con el jefe directo.",
          "Identificar oportunamente los riegos de incumplimiento y cambios sobre las condiciones iniciales de los contratos."
        ]
      },
      {
        "title": "ADMINISTRADOR DE CONTRATOS SR - OPERACIONES",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "8",
        "experience_position": "3",
        "experience_sector": "4",
        "carrera_afin": "ADMINISTRACIÓN DE EMPRESAS\nDERECHO\nINGENIERÍA CIVIL\nINGENIERÍA DE MINAS\nINGENIERÍA DE SISTEMAS\nINGENIERÍA ELECTRONICA\nINGENIERÍA EMPRESARIAL\nINGENIERÍA ESTADISTICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Revisar y mantener actualizada la información del plan de contratación de servicios reportando las desviaciones que ponen en riesgo el cumplimiento de las actividades planeadas.",
          "Gestionar los requerimientos (SOLPEDS) de Alta Complejidad liderando los procesos de contratación por montos mayores a US$ 1MM",
          "Gestionar las etapas del concurso (aprobación de postores, visita a terreno, absolución de consultas, evaluación, adjudicación, etc) y coordinar con el usuario solicitante la elección final del proveedor y negociación de los mejores términos y condiciones.",
          "Revisar los documentos recibidos del usuario (SOW, especificaciones técnicas, presupuesto base, etc)",
          "Realizar la evaluación de las propuestas económicas y condiciones de entrega en coordinación con el área solicitante.",
          "Elaborar el cronograma de concurso, lista de postores y documentos de concurso (bases, cartas de invitación, etc) en coordinación con el usuario solicitante.",
          "Gestionar la administración contractual y aprobación de valorizaciones, reclamos, penalidades, correspondencia contractual y reportar las contrataciones frecuentes que pueden ser negociadas mediante Acuerdo de Precios, Consignación u otros con proveedores, así como el respectivo cierre de contrato.",
          "Preparar, consolidar y custodiar la documentación de adjudicación y contractual, coordinando con el proveedor seleccionado lo necesario para la admisión del personal del proveedor a las instalaciones de MCP.",
          "Realizar evaluaciones periódicas del desempeño de los proveedores en coordinación con el jefe directo.",
          "Identificar oportunamente los riegos de incumplimiento y cambios sobre las condiciones iniciales de los contratos."
        ]
      },
      {
        "title": "ADMINISTRADOR DE CONTRATOS SR - PROYECTOS",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "8",
        "experience_position": "3",
        "experience_sector": "4",
        "carrera_afin": "ADMINISTRACIÓN DE EMPRESAS\nDERECHO\nINGENIERÍA CIVIL\nINGENIERÍA DE MINAS\nINGENIERÍA DE SISTEMAS\nINGENIERÍA ELECTRONICA\nINGENIERÍA EMPRESARIAL\nINGENIERÍA ESTADISTICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA\nCONTABILIDAD",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Revisar y mantener actualizada la información del plan de contratación de servicios reportando las desviaciones que ponen en riesgo el cumplimiento de las actividades planeadas.",
          "Gestionar los requerimientos (SOLPEDS) de Alta Complejidad liderando los procesos de contratación por montos mayores a US$ 1MM",
          "Gestionar las etapas del concurso (aprobación de postores, visita a terreno, absolución de consultas, evaluación, adjudicación, etc) y coordinar con el usuario solicitante la elección final del proveedor y negociación de los mejores términos y condiciones.",
          "Revisar los documentos recibidos del usuario (SOW, especificaciones técnicas, presupuesto base, etc)",
          "Realizar la evaluación de las propuestas económicas y condiciones de entrega en coordinación con el área solicitante.",
          "Elaborar el cronograma de concurso, lista de postores y documentos de concurso (bases, cartas de invitación, etc) en coordinación con el usuario solicitante.",
          "Gestionar la administración contractual y aprobación de valorizaciones, reclamos, penalidades, correspondencia contractual y reportar las contrataciones frecuentes que pueden ser negociadas mediante acuerdo de precios, consignación u otros con proveedores, así como el respectivo cierre de contrato.",
          "Preparar, consolidar y custodiar la documentación de adjudicación y contractual, coordinando con el proveedor seleccionado lo necesario para la admisión del personal del proveedor a las instalaciones de MCP.",
          "Realizar evaluaciones periódicas del desempeño de los proveedores en coordinación con el jefe directo.",
          "Identificar oportunamente los riegos de incumplimiento y cambios sobre las condiciones iniciales de los contratos."
        ]
      },
      {
        "title": "ADMINISTRADOR DE GARANTIAS Y REPARACIONES 1",
        "category": "Analista",
        "level": "Nivel 6",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "6",
        "experience_position": "4",
        "experience_sector": "3",
        "carrera_afin": "INGENIERÍA ELECTRONICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Proceder con la venta de los activos y materiales adquiridos que hayan sido identificados como obsoletos.",
          "Desarrollar contratos MARCO de reparación de componentes mayores y menores en coordinación con el área usuaria, encargándose de los procesos de concurso y administración de contratos para los contratos MARCO.",
          "Coordinar con las áreas de mantenimiento y control de inventario, estableciendo los requerimientos de las áreas usuarias y manteniendo un nivel de inventario óptimo.",
          "Establecer las garantías y vida útil mínima de la reparación de los componentes a ser reparados en los contratos MARCO, encargándose del proceso de reclamo por garantía para aquellos componentes que fallen antes de su vida útil de la reparación pactada en los contratos.",
          "Gestionar los componentes reparables de los equipos nuevos que adquiera MCP en coordinación con el usuario, manteniendo una cantidad de componentes que permita una disponibilidad mínima del equipo.",
          "Identificar las necesidades de componentes reparables en coordinación con los planners de mantenimiento.",
          "Participar en el proceso de validación el Plan Anual de Cambio de Componentes propuesto por el área de mantenimiento, evaluando la disponibilidad de componentes para su ejecución."
        ]
      },
      {
        "title": "ASISTENTE DE CONTRATOS - PROYECTOS",
        "category": "Auxiliar",
        "level": "Nivel 2",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "2",
        "experience_position": "1",
        "experience_sector": "1",
        "carrera_afin": "DERECHO\nINGENIERÍA CIVIL\nINGENIERÍA DE MINAS\nINGENIERÍA DE SISTEMAS\nADMINISTRACIÓN DE EMPRESAS",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Dar soporte en la revisión y actualización de la información del plan de contratación de servicios reportando las desviaciones que ponen en riesgo el cumplimiento de las actividades planeadas.",
          "Dar soporte en la gestión de los requerimientos (SOLPEDS) de Baja y Mediana Complejidad, apoyando en los procesos de contratación por montos hasta US$ 500,000",
          "Dar soporte en la gestión de las etapas del concurso (aprobación de postores, visita a terreno, absolución de consultas, evaluación, adjudicación, etc) y coordinar con el usuario solicitante la elección final del proveedor y negociación de los mejores términos y condiciones.",
          "Revisar los documentos recibidos del usuario (SOW, especificaciones técnicas, presupuesto base, etc)",
          "Dar soporte en la evaluación de las propuestas económicas y condiciones de entrega en coordinación con el área solicitante.",
          "Elaborar el cronograma de concurso, lista de postores y documentos de concurso (bases, cartas de invitación, etc) en coordinación con el usuario solicitante.",
          "Dar soporte en la administración contractual y aprobación de valorizaciones, reclamos, penalidades, correspondencia contractual y reportar las contrataciones frecuentes que pueden ser negociadas mediante Acuerdo de Precios, Consignación u otros con proveedores, así como el respectivo cierre de contrato.",
          "Preparar, consolidar y custodiar la documentación de adjudicación y contractual, coordinando con el proveedor seleccionado lo necesario para la admisión del personal del proveedor a las instalaciones de MCP.",
          "Realizar evaluaciones periódicas del desempeño de los proveedores en coordinación con el jefe directo.",
          "Identificar oportunamente los riegos de incumplimiento y cambios sobre las condiciones iniciales de los contratos."
        ]
      },
      {
        "title": "ASISTENTE DE GARANTIAS Y REPARACIONES",
        "category": "Auxiliar",
        "level": "Nivel 1",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "1",
        "experience_position": "1",
        "experience_sector": "1",
        "carrera_afin": "INGENIERÍA ELECTRONICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Dar soporte en el seguimiento y coordinaciones requeridas durante la ejecución de contratos vigentes.",
          "Participar la coordinación entre las áreas usuarias y control de inventario respecto a la identificación de requerimientos de las áreas usuarias.",
          "Dar soporte en el proceso de gestión de componentes reparables de los equipos nuevos que adquiera MCP, dando seguimiento al stock de componentes que permita contar con la disponibilidad de componentes reparados.",
          "Dar soporte en la identificación de componentes reparables en coordinación con los planners de mantenimiento.",
          "Dar soporte en la elaboración los reportes e informes requeridos."
        ]
      },
      {
        "title": "COMPRADOR 1 - OPERACIONES",
        "category": "Analista",
        "level": "Nivel 5",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "5",
        "experience_position": "3",
        "experience_sector": "3",
        "carrera_afin": "INGENIERÍA CIVIL\nINGENIERÍA DE MINAS\nINGENIERÍA DE SISTEMAS\nINGENIERÍA ELECTRONICA\nINGENIERÍA EMPRESARIAL\nINGENIERÍA ESTADISTICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA\nCONTABILIDAD\nADMINISTRACIÓN",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Revisar y mantener actualizada la información del plan de adquisición de bienes reportando las desviaciones que ponen en riesgo el cumplimiento de las actividades planeadas.",
          "Gestionar los requerimientos (SOLPEDS) de mediana complejidad liderando los procesos de adquisición por montos entre US$ 500,000 y US$ 1MM",
          "Gestionar las etapas del concurso (aprobación de postores, visita a terreno, absolución de consultas, evaluación, adjudicación, etc) y coordinar con el usuario solicitante la elección final del proveedor y negociación de los mejores términos y condiciones.",
          "Revisar los documentos recibidos del usuario (SOW, especificaciones técnicas, presupuesto base, etc)",
          "Realizar la evaluación de las propuestas económicas y condiciones de entrega en coordinación con el área solicitante",
          "Elaborar el cronograma de concurso, lista de postores y documentos de concurso (bases, cartas de invitación, etc) en coordinación con el usuario solicitante.",
          "Gestionar la aprobación de valorizaciones, reclamos, penalidades, correspondencia contractual y reportar las adquisiciones frecuentes que pueden ser negociadas mediante Acuerdo de Precios, Consignación u otros con proveedores.",
          "Preparar, consolidar y custodiar la documentación de adjudicación y contractual, coordinando con el proveedor seleccionado lo necesario para la admisión del personal del proveedor a las instalaciones de MCP.",
          "Realizar evaluaciones periódicas del desempeño de los proveedores en coordinación con el jefe directo."
        ]
      },
      {
        "title": "COMPRADOR 1 - PROYECTOS",
        "category": "Analista",
        "level": "Nivel 5",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "5",
        "experience_position": "3",
        "experience_sector": "3",
        "carrera_afin": "INGENIERÍA CIVIL\nINGENIERÍA DE MINAS\nINGENIERÍA DE SISTEMAS\nINGENIERÍA ELECTRONICA\nINGENIERÍA EMPRESARIAL\nINGENIERÍA ESTADISTICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA\nADMINISTRACIÓN\nCONTABILIDAD",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Revisar y mantener actualizada la información del plan de adquisición de bienes reportando las desviaciones que ponen en riesgo el cumplimiento de las actividades planeadas.",
          "Gestionar los requerimientos (SOLPEDS) de mediana complejidad liderando los procesos de adquisición por montos entre US$ 500,000 y US$ 1MM",
          "Gestionar las etapas del concurso (aprobación de postores, visita a terreno, absolución de consultas, evaluación, adjudicación, etc) y coordinar con el usuario solicitante la elección final del proveedor y negociación de los mejores términos y condiciones.",
          "Revisar los documentos recibidos del usuario (SOW, especificaciones técnicas, presupuesto base, etc)",
          "Realizar la evaluación de las propuestas económicas y condiciones de entrega en coordinación con el área solicitante",
          "Elaborar el cronograma de concurso, lista de postores y documentos de concurso (bases, cartas de invitación, etc) en coordinación con el usuario solicitante.",
          "Gestionar la aprobación de valorizaciones, reclamos, penalidades, correspondencia contractual y reportar las adquisiciones frecuentes que pueden ser negociadas mediante Acuerdo de Precios, Consignación u otros con proveedores.",
          "Preparar, consolidar y custodiar la documentación de adjudicación y contractual, coordinando con el proveedor seleccionado lo necesario para la admisión del personal del proveedor a las instalaciones de MCP.",
          "Realizar evaluaciones periódicas del desempeño de los proveedores en coordinación con el jefe directo."
        ]
      },
      {
        "title": "COMPRADOR 2 - OPERACIONES",
        "category": "Asistente",
        "level": "Nivel 3",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "3",
        "experience_position": "2",
        "experience_sector": "2",
        "carrera_afin": "INGENIERÍA CIVIL\nINGENIERÍA DE MINAS\nINGENIERÍA DE SISTEMAS\nINGENIERÍA ELECTRONICA\nINGENIERÍA EMPRESARIAL\nINGENIERÍA ESTADISTICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA\nCONTABILIDAD\nADMINISTRACIÓN",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Revisar y mantener actualizada la información del plan de adquisición de bienes reportando las desviaciones que ponen en riesgo el cumplimiento de las actividades planeadas.",
          "Gestionar los requerimientos (SOLPEDS) de baja y mediana complejidad liderando los procesos de adquisición por montos hasta US$ 500,000",
          "Gestionar las etapas del concurso (aprobación de postores, visita a terreno, absolución de consultas, evaluación, adjudicación, etc) y coordinar con el usuario solicitante la elección final del proveedor y negociación de los mejores términos y condiciones.",
          "Revisar los documentos recibidos del usuario (SOW, especificaciones técnicas, presupuesto base, etc)",
          "Realizar la evaluación de las propuestas económicas y condiciones de entrega en coordinación con el área solicitante.",
          "Elaborar el cronograma de concurso, lista de postores y documentos de concurso (bases, cartas de invitación, etc) en coordinación con el usuario solicitante.",
          "Gestionar la aprobación de valorizaciones, reclamos, penalidades, correspondencia contractual y reportar las adquisiciones frecuentes que pueden ser negociadas mediante Acuerdo de Precios, Consignación u otros con proveedores.",
          "Preparar, consolidar y custodiar la documentación de adjudicación y contractual, coordinando con el proveedor seleccionado lo necesario para la admisión del personal del proveedor a las instalaciones de MCP.",
          "Realizar evaluaciones periódicas del desempeño de los proveedores en coordinación con el jefe directo."
        ]
      },
      {
        "title": "COMPRADOR SR - OPERACIONES",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "8",
        "experience_position": "3",
        "experience_sector": "4",
        "carrera_afin": "INGENIERÍA CIVIL\nINGENIERÍA DE MINAS\nINGENIERÍA DE SISTEMAS\nINGENIERÍA ELECTRONICA\nINGENIERÍA EMPRESARIAL\nINGENIERÍA ESTADISTICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA\nINGENIERÍA COMERCIAL\nCONTABILIDAD",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Revisar y mantener actualizada la información del plan de adquisición de bienes reportando las desviaciones que ponen en riesgo el cumplimiento de las actividades planeadas.",
          "Gestionar los requerimientos (SOLPEDS) de alta complejidad liderando los procesos de adquisición por montos mayores a US$ 1MM",
          "Gestionar las etapas del concurso (aprobación de postores, visita a terreno, absolución de consultas, evaluación, adjudicación, etc) y coordinar con el usuario solicitante la elección final del proveedor y negociación de los mejores términos y condiciones.",
          "Revisar los documentos recibidos del usuario (SOW, especificaciones técnicas, presupuesto base, etc)",
          "Realizar la evaluación de las propuestas económicas y condiciones de entrega en coordinación con el área solicitante.",
          "Elaborar el cronograma de concurso, lista de postores y documentos de concurso (bases, cartas de invitación, etc) en coordinación con el usuario solicitante.",
          "Gestionar la aprobación de valorizaciones, reclamos, penalidades, correspondencia contractual y reportar las adquisiciones frecuentes que pueden ser negociadas mediante Acuerdo de Precios, Consignación u otros con proveedores.",
          "Preparar, consolidar y custodiar la documentación de adjudicación y contractual, coordinando con el proveedor seleccionado lo necesario para la admisión del personal del proveedor a las instalaciones de MCP.",
          "Realizar evaluaciones periódicas del desempeño de los proveedores en coordinación con el jefe directo"
        ]
      },
      {
        "title": "COMPRADOR SR - PROYECTOS",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "ADMINISTRACIÓN",
        "speciality": "ADMINISTRACIÓN",
        "experience_general": "8",
        "experience_position": "3",
        "experience_sector": "4",
        "carrera_afin": "INGENIERÍA CIVIL\nINGENIERÍA DE MINAS\nINGENIERÍA DE SISTEMAS\nINGENIERÍA ELECTRONICA\nINGENIERÍA EMPRESARIAL\nINGENIERÍA ESTADISTICA\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Revisar y mantener actualizada la información del plan de adquisición de bienes reportando las desviaciones que ponen en riesgo el cumplimiento de las actividades planeadas.",
          "Gestionar los requerimientos (SOLPEDS) de alta complejidad liderando los procesos de adquisición por montos mayores a US$ 1MM",
          "Gestionar las etapas del concurso (aprobación de postores, visita a terreno, absolución de consultas, evaluación, adjudicación, etc) y coordinar con el usuario solicitante la elección final del proveedor y negociación de los mejores términos y condiciones.",
          "Revisar los documentos recibidos del usuario (SOW, especificaciones técnicas, presupuesto base, etc)",
          "Realizar la evaluación de las propuestas económicas y condiciones de entrega en coordinación con el área solicitante.",
          "Elaborar el cronograma de concurso, lista de postores y documentos de concurso (bases, cartas de invitación, etc) en coordinación con el usuario solicitante.",
          "Gestionar la aprobación de valorizaciones, reclamos, penalidades, correspondencia contractual y reportar las adquisiciones frecuentes que pueden ser negociadas mediante Acuerdo de Precios, Consignación u otros con proveedores.",
          "Preparar, consolidar y custodiar la documentación de adjudicación y contractual, coordinando con el proveedor seleccionado lo necesario para la admisión del personal del proveedor a las instalaciones de MCP.",
          "Realizar evaluaciones periódicas del desempeño de los proveedores en coordinación con el jefe directo"
        ]
      },
      {
        "title": "COORDINADOR SR DE GESTION INFORMACION HQ Y COMPRAS",
        "category": "Analista",
        "level": "Nivel 5",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "5",
        "experience_position": "3",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN DE EMPRESAS\nCONTABILIDAD",
        "idioma": "Inglés\nChino",
        "nivel": "Intermedio\nIntermedio",
        "functions": [
          "Realizar estudios / análisis especiales y atención de trabajos solicitados por el Vicepresidente comercial respecto a su gestión.",
          "Elaborar los reportes e informes requeridos, incluyendo comunicaciones con funcionarios de la casa matriz y proveedores chinos respecto al alcance, tiempo, costo y calidad de adquisición de bienes.",
          "Coordinar la atención de las actividades requeridas en las etapas de los concursos (aprobación de postores, visita a terreno, absolución de consultas, evaluación, adjudicación, etc) y dar soporte en las comunicaciones con el usuario solicitante respecto a la elección final del proveedor y, incluyendo la negociación de los mejores términos y condiciones",
          "Coordinar la atención de las actividades requeridas en la administración contractual y aprobación de valorizaciones, reclamos, penalidades, correspondencia contractual y reportar las contrataciones frecuentes que pueden ser negociadas mediante Acuerdo de Precios, Consignación u otros con proveedores, así como el respectivo cierre de contrato.",
          "Coordinar la atención de las actividades requeridas en la atención de requerimientos (SOLPEDS), liderando los procesos de adquisición requeridos.",
          "Coordinar la atención de las actividades requeridas en la evaluación de las propuestas económicas y condiciones de entrega en coordinación con el área solicitante."
        ]
      },
      {
        "title": "EXPEDITOR SR - OPERACIONES",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "8",
        "experience_position": "3",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN\nARQUITECTURA\nCONTABILIDAD\nINGENIERÍA CIVIL\nINGENIERÍA MECANICA\nNEGOCIOS INTERNACIONALES",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Monitorear el envío materiales y equipos requeridos para las operaciones de MCP de acuerdo al cronograma comprometido, en coordinación con los proveedores.",
          "Actualizar la información del reporte de seguimiento de entregas.",
          "Verificar la ejecución de las etapas de fabricación y despacho de las órdenes de compra con pagos parciales, autorizando el pago de anticipos y respectivo cierre de ordenes de compra.",
          "Gestionar planes de contingencia ante la ocurrencia de problemas en el envío de materiales y equipos críticos para las operaciones de MCP, autorizando envíos aéreos en caso se requiera.",
          "Realizar el seguimiento y liberación de pagos parciales de acuerdo a las condiciones pactadas en las PO's o contratos de suministro"
        ]
      },
      {
        "title": "JEFE DE COMPRAS - OPERACIONES",
        "category": "Jefe",
        "level": "Nivel 10",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "10",
        "experience_position": "5",
        "experience_sector": "5",
        "carrera_afin": "ADMINISTRACIÓN\nECONOMÍA",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Elaborar, en coordinación con el Superintendente de Compras y Contratos y las áreas de la operación de la empresa, el plan de adquisiciones de bienes para el corto, mediano y largo plazo, categorizando las necesidades de acuerdo a su criticidad (alta, media o baja).",
          "Coordinar con los compradores la negociación frente a los proveedores (respecto a fechas, precios, estrategias de negociación, etc.).",
          "Evaluar las propuestas y negociar términos y condiciones favorables para la empresa.",
          "Administrar los contratos de suministro y convenios, coordinando las firmas y aprobaciones respectivas",
          "Evaluar periódicamente el ranking de fiabilidad por tipo de proveedor  de bienes y proponer acciones correctivas para aquellos proveedores con un patrón de incumplimientos fuera de rango.",
          "Monitorear el desempeño del equipo de Compradores a su cargo y apoyar a su gestión."
        ]
      },
      {
        "title": "JEFE DE COMPRAS - PROYECTOS",
        "category": "Jefe",
        "level": "Nivel 10",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "10",
        "experience_position": "5",
        "experience_sector": "5",
        "carrera_afin": "ADMINISTRACIÓN\nECONOMÍA",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Elaborar, en coordinación con el Superintendente de Compras y Contratos y las áreas de la operación y proyectos de la empresa, el plan de adquisiciones de bienes para el corto, mediano y largo plazo, categorizando las necesidades de acuerdo a su criticidad (alta, media o baja)",
          "Coordinar con los compradores la negociación frente a los proveedores (respecto a fechas, precios, estrategias de negociación, etc.).",
          "Evaluar las propuestas y negociar términos y condiciones favorables para la empresa.",
          "Administrar los contratos y convenios, coordinando las firmas y aprobaciones respectivas",
          "Evaluar periódicamente el ranking de fiabilidad por tipo de proveedor de bienes y proponer acciones correctivas para aquellos proveedores con un patrón de incumplimientos fuera de rango.",
          "Monitorear el desempeño del equipo de Compradores a su cargo y apoyar a su gestión."
        ]
      },
      {
        "title": "JEFE DE CONTRATOS - OPERACIONES",
        "category": "Jefe",
        "level": "Nivel 10",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "10",
        "experience_position": "5",
        "experience_sector": "5",
        "carrera_afin": "ADMINISTRACIÓN\nECONOMÍA\nINGENIERIAS AFINES",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Elaborar, en coordinación con el Superintendente de Compras y Contratos y las áreas de la operación y proyectos de la empresa, el plan de adquisiciones de servicios para el corto, mediano y largo plazo, categorizando las necesidades de acuerdo a su criticidad (alta, media o baja).",
          "Dar seguimiento al proceso de adquisición de servicios.",
          "Administrar los contratos y convenios, coordinando las firmas y aprobaciones respectivas.",
          "Evaluar periódicamente el ranking de fiabilidad por tipo de proveedor  de servicios y proponer acciones correctivas para aquellos proveedores con un patrón de incumplimientos fuera de rango.",
          "Monitorear el desempeño del equipo de Administradores de Contrato a su cargo y apoyar a su gestión."
        ]
      },
      {
        "title": "JEFE DE CONTRATOS - PROYECTOS",
        "category": "Jefe",
        "level": "Nivel 10",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "10",
        "experience_position": "5",
        "experience_sector": "5",
        "carrera_afin": "ADMINISTRACIÓN\nECONOMÍA\nINGENIERIAS AFINES",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Elaborar, en coordinación con el Superintendente de Compras y Contratos y las áreas de la operación y proyectos de la empresa, el plan de adquisiciones de servicios para el corto, mediano y largo plazo, categorizando las necesidades de acuerdo a su criticidad (alta, media o baja).",
          "Dar seguimiento al proceso de adquisición de servicios.",
          "Administrar los contratos y convenios, coordinando las firmas y aprobaciones respectivas.",
          "Evaluar periódicamente el ranking de fiabilidad por tipo de proveedor de servicios y proponer acciones correctivas para aquellos proveedores con un patrón de incumplimientos fuera de rango.",
          "Monitorear el desempeño del equipo de Administradores de Contrato a su cargo y apoyar a su gestión."
        ]
      },
      {
        "title": "JEFE DE GARANTIAS Y REPARACIONES",
        "category": "Jefe",
        "level": "Nivel 10",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "10",
        "experience_position": "8",
        "experience_sector": "4",
        "carrera_afin": "INGENIERÍA ELECTRONICA\nINGENIERÍA MECANICA\nINGENIERÍA MECÁNICA Y ELÉCTRICA",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Evaluar las necesidades de componentes reparables en coordinación con el área usuaria, manteniendo un nivel de inventario óptimo.",
          "Negociar tarifas competitivas para el proceso de reparación de componentes mayores y menores.",
          "Hacer seguimiento al rendimiento de los componentes, efectuando los reclamos de garantía en aquellos cuyos rendimientos no alcancen lo pactado con el proveedor contractualmente.",
          "Monitorear el total de componentes disponibles para los equipos y flotas (nuevos, reparados, en procesos de reparación, en uso).",
          "Obtener los mayores beneficios por la venta de componentes, repuestos, insumos y/o equipos dados de baja.",
          "Solicitar y validar el Plan Anual de Cambio de Componentes Mayores y Menores de Mina y Planta en coordinacion con las superintendencias de mantenimiento.",
          "Revisar el Plan Anual de Ejecución de Contratos MARCO, participando en las principales negociaciones."
        ]
      },
      {
        "title": "SUPERINTENDENTE DE COMPRAS Y CONTRATOS",
        "category": "Superintendente",
        "level": "Nivel 12",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "12",
        "experience_position": "10",
        "experience_sector": "4",
        "carrera_afin": "ADMINISTRACIÓN\nINGENIERIAS AFINES",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Dirigir, planificar y controlar los procesos de adquisición de bienes y contratación de servicios para operaciones y proyectos de MCP.",
          "Formular el Plan de Adquisición de Bienes y Contratación Servicios de corto, mediano y largo plazo, categorizando las necesidades de acuerdo a su criticidad (alta, media o baja) en coordinación con las jefaturas del área.",
          "Revisar los concursos y contratos de adquisición de bienes y servicios, validando su cumplimiento en relación a las políticas y procedimientos de MCP.",
          "Controlar las actividades de homologación de empresas proveedoras de bienes y servicios de acuerdo al perfil definido por MCP.",
          "Revisar y aprobar las órdenes de compra y servicios generadas por los Compradores / Administradores de Contratos previamente aprobadas por las jefaturas de las áreas a cargo.",
          "Evaluar las oportunidades de generación de Acuerdo de Precios con proveedores, en coordinación con el área de Almacenes y Control de Inventario.",
          "Participar en las negociaciones de los principales contratos de operaciones y proyectos, así como en las principales reuniones que involucren decisiones mayores.",
          "Participar en reuniones periódicas con las distintas gerencias y sus equipos, tocando temas de interés mutuo y estableciendo planes de trabajo conjunto, generando compromisos con entregables especificos.",
          "Dirigir, planificar y coordinar con el área de proyectos respecto al Plan Anual de Requerimientos de bienes y servicios, actualizándolo de forma trimestral."
        ]
      }
    ],
    "functions": [],
    "x": 340,
    "y": 280
  },
  {
    "id": "direccion-de-logistica-y-comercial",
    "title": "Dirección de Logistica y Comercial",
    "icon": "💼",
    "summary": "Área de Dirección de Logistica y Comercial",
    "accent": "#10B981",
    "color": "#10B981",
    "departmentTitle": "Gerencia de Dirección de Logistica y Comercial",
    "description": "Coordinar, administrar y ejecutar los trabajos referentes a la integración, control y reportabilidad de información de los procesos de la Dirección de Logística y Comercial, en tiempo real, mediante el ERP y sistemas de información a fin de asegurar la calidad de la información administrada y utilizada en los procesos de toma de decisiones.",
    "npc": "Gerente",
    "npcRole": "Responsable de Dirección de Logistica y Comercial",
    "quote": "Bienvenido al área de Dirección de Logistica y Comercial",
    "competencies": [],
    "mapLabel": "Dirección",
    "positions": [
      {
        "title": "COORDINADOR SR DE COSTOS Y SISTEMAS DE LOGISTICA Y COMERCIAL",
        "category": "Analista",
        "level": "Nivel 5",
        "blurb": "INGENIERÍA DE SISTEMAS",
        "speciality": "INGENIERÍA DE SISTEMAS",
        "experience_general": "5",
        "experience_position": "1",
        "experience_sector": "2",
        "carrera_afin": "INGENIERÍA INDUSTRIAL\nINGENIERÍA INFORMÁTICA\nADMINISTRACIÓN DE BASE DE DATOS\nADMINISTRACIÓN",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Administrar y dar soporte en el modulo MM en el sistema SAP a todos los usuarios del módulo.",
          "Administrar los modulos de SLP, DSN, Sourcing y Contracts en ARIBA",
          "Coordinar mejoras al sistemas, solicitadas por usuarios finales, e implementarlas a través del contratista de desarrollo de sistemas (sistema de gestión de contratos, SAP, TRADER, WAPSA, B2B)",
          "Validar el tiempo y costo de las optimizaciones de sistemas (SAP) solicitados al contratista.",
          "Verificar la calidad de los datos y principales indicadores de gestión de la Dirección de Lógistica y Comercial.",
          "Validar el tiempo y costo de los desarrollos de sistemas (TRADER, WAPSA) solicitados al contratista.",
          "Definir el establishment dentro del sistema SAP para creación de flujos de aprobaciones.",
          "Brindar entrenamiento para la creación de transaciones SAP dentro de la Dirección de Logistica y Comercial.",
          "Coordinar y ejecutar las actividades referidas al control de costos de la Dirección de Logística y Comercial.",
          "Elaborar los reportes de control requeridos, respecto a la gestión de las distintas áreas de la Dirección de Logística y Comercial.",
          "Realizar el seguimiento y coordinar los reportes de auditoria HQ y auditoria interna con las áreas involucradas."
        ]
      },
      {
        "title": "SUPERVISOR DE CONTROL DE COSTOS Y SISTEMAS",
        "category": "Supervisor",
        "level": "Nivel 7",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "7",
        "experience_position": "4",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN DE EMPRESAS\nINGENIERÍA DE SISTEMAS",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Dar soporte en la formulación de presupuesto OPEX asociados a la Gerencia de Logística y Comercial",
          "Dar soporte en la formulación de presupuesto CAPEX asociados a la Gerencia de Logística y Comercial",
          "Emitir quincenalmente los reportes de control de presupuesto CAPEX de las áreas de la Gerencia de Logística y Comercial",
          "Emitir mensualmente los reportes de control de presupuesto OPEX de las áreas de la Gerencia de Logística y Comercial",
          "Supervisar funcionamiento adecuado de los sistemas de la Gerencia de Logística y Comercial ( SAP modulo MM, sistema de gestión de contratos, WAPSA, TRADER)",
          "Evaluar y priorizar los proyectos de desarrollo de sistemas requeridos por las distintas áreas de la Gerencia de Logística y Comercial.",
          "Coordinar y/o elaborar los reportes especiales de control de las distintas áreas de Logística y Comercial, Auditoria Interna, Casa Matriz y otras áreas de MCP.",
          "Consolidar y administrar los resultados de KPI en forma mensual.",
          "Dimensionar los costos indirectos de items críticos de la empresa.",
          "Controlar los costos indirectos (proyectado, control y ajuste)",
          "Cierre de todos los pedidos desde el 2014-2020, que no hayan sido cerrados/ compensados en el sistema, realizar un cierre forzoso."
        ]
      }
    ],
    "functions": [],
    "x": 420,
    "y": 340
  },
  {
    "id": "planeamiento-de-inventario",
    "title": "Planeamiento de Inventario",
    "icon": "📊",
    "summary": "Área de Planeamiento de Inventario",
    "accent": "#06B6D4",
    "color": "#06B6D4",
    "departmentTitle": "Gerencia de Planeamiento de Inventario",
    "description": "Gestionar los procesos de planificación, coordinación y control de los niveles de inventarios en los almacenes de la Unidad Minera Toromocho (Mina y Planta), determinando niveles óptimos de stock para los diferentes grupos de artículos, evaluando y proponiendo procedimientos y políticas a fin de asegurar un adecuado nivel de servicio.",
    "npc": "Gerente",
    "npcRole": "Responsable de Planeamiento de Inventario",
    "quote": "Bienvenido al área de Planeamiento de Inventario",
    "competencies": [],
    "mapLabel": "Planeamiento",
    "positions": [
      {
        "title": "JEFE DE PLANEAMIENTO DE INVENTARIO",
        "category": "Jefe",
        "level": "Nivel 10",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "10",
        "experience_position": "5",
        "experience_sector": "5",
        "carrera_afin": "ADMINISTRACIÓN\nINGENIERÍA DE SISTEMAS",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Diseñar y controlar los planes de reposición inventarios en base a los tiempos de aprovisionamiento, monitoreando la rotación de los repuestos del almacén.",
          "Definir el programa de reposición para materiales clasificados como \"items rutinarios\", \"items críticos\" e \"items de seguridad\".",
          "Monitorear y cuantificar los niveles de inventario necesarios en los almacenes de la U.M. Toromocho.",
          "Controlar el presupuesto del área reportando a la superintendencia.",
          "Formular y actualizar los procedimientos de los procesos a cargo, implementando las mejores practicas de control de inventarios.",
          "Proponer la revisión de los items inactivos a las áreas usuarias, obteniendo la confirmación de la obsolescencia por parte de las áreas usuarias para su posterior disposición."
        ]
      },
      {
        "title": "PLANIFICADOR DE INVENTARIO",
        "category": "Analista",
        "level": "Nivel 5",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "5",
        "experience_position": "3",
        "experience_sector": "2",
        "carrera_afin": "ADMINISTRACIÓN DE EMPRESAS",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Catalogar los nuevos materiales a usarse en la operación, de acuerdo a los requerimientos de los diferentes usuarios y las políticas de inventario de MCP.",
          "Gestionar el abastecimiento de insumos y repuestos en función a las metodologías de reposición definidas y estadísticas de consumo, confirmando las reposiciones de los materiales de stock bajo su cargo y coordinando con el área de compras / usuario de componentes",
          "Aplicar las estrategias de reposición de inventarios definidas.",
          "Identificar demandas futuras de ítems específicos en función a los planes de producción de la empresa, validando los hallazgos con las áreas usuarias.",
          "Proponer alternativas de recuperación de inversión, identificando materiales inactivos en función a la ausencia de consumos y confirmar con los usuarios la condición de estos como obsoletos."
        ]
      },
      {
        "title": "PLANIFICADOR DE INVENTARIO SR",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "8",
        "experience_position": "3",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN DE EMPRESAS",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Catalogar los nuevos materiales a usarse en la operación, de acuerdo a los requerimientos de los diferentes usuarios y las políticas de inventario de MCP.",
          "Gestionar el abastecimiento de insumos y repuestos en función a las metodologías de reposición definidas y estadísticas de consumo, confirmando las reposiciones de stock materiales críticos bajo su cargo y coordinando con el área de compras / usuario de componentes",
          "Evaluar las estrategias de reposición de inventarios, controlando su ejecución y realizando los reportes de gestión requeridos.",
          "Identificar demandas futuras de ítems específicos en función a los planes de producción de la empresa, validando los hallazgos con las áreas usuarias y coordinando la ejecución de planes de accion requeridos.",
          "Proponer alternativas de recuperación de inversión, identificando materiales inactivos en función a la ausencia de consumos y confirmar con los usuarios la condición de estos como obsoletos."
        ]
      }
    ],
    "functions": [],
    "x": 500,
    "y": 400
  },
  {
    "id": "transporte-y-trafico-internacional",
    "title": "Transporte y Tráfico Internacional",
    "icon": "🏢",
    "summary": "Área de Transporte y Tráfico Internacional",
    "accent": "#EF4444",
    "color": "#EF4444",
    "departmentTitle": "Gerencia de Transporte y Tráfico Internacional",
    "description": "Coordinar, administrar y ejecutar los trabajos referentes al control de las labores propias del almacén de transito (recepción, almacenamiento y despacho de materiales), el correcto uso de los procedimientos así como los equipos adecuados para estas actividades, verificando el ingreso correcto de la información  a los sistema para el control de los stock y coordinando con logística mina para el envío de las cargas, a fin de garantizar la ejecución de las actividades propias del almacén de transito.",
    "npc": "Gerente",
    "npcRole": "Responsable de Transporte y Tráfico Internacional",
    "quote": "Bienvenido al área de Transporte y Tráfico Internacional",
    "competencies": [],
    "mapLabel": "Transporte",
    "positions": [
      {
        "title": "COORDINADOR SR DE ALMACEN DE TRANSITO",
        "category": "Analista",
        "level": "Nivel 6",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "6",
        "experience_position": "4",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN",
        "idioma": "Inglés",
        "nivel": "Intermedio",
        "functions": [
          "Administrar, controlar y dar conformidad a las guías de materiales que lleguen al almacén de tránsito.",
          "Monitorear y coordinar las labores de descarga, recepción, almacenamiento y despacho de materiales en el Almacén",
          "Coordinar, controlar y verificar la cantidad, calidad de los materiales entregados por los proveedores y transportistas.",
          "Monitorear y coordinar el uso de equipos para las actividades propias del Almacén de Tránsito como la recepción, almacenamiento y despacho (camión grúas y montacargas)",
          "Coordinar, controlar e ingresar en el sistema de manera oportuna las recepciones de materiales en el ERP",
          "Monitorear y coordinar los inventarios rotativos e inventarios programados por control interno, en los diferentes almacenes de Tránsito",
          "Actualizar los KPI que se generen para el control de la gestión del almacén de transito.",
          "Atender los requerimientos y solicitudes de los usuarios finales en mina mediante comunicación constante.",
          "Controlar los procesos de la gestión del almacén y el cumplimiento de las políticas, procedimientos, estándares e indicadores logísticos del almacén"
        ]
      },
      {
        "title": "COORDINADOR SR DE OPERACIONES FERROVIARIAS",
        "category": "Analista",
        "level": "Nivel 6",
        "blurb": "INGENIERÍA METALURGICA",
        "speciality": "INGENIERÍA METALURGICA",
        "experience_general": "6",
        "experience_position": "4",
        "experience_sector": "3",
        "carrera_afin": "ADMINISTRACIÓN DE EMPRESAS\nINGENIERIAS AFINES\nINGENIERÍA INDUSTRIAL\nINGENIERÍA MECANICA",
        "idioma": "Inglés",
        "nivel": "Básico",
        "functions": [
          "Realizar el seguimiento de los vagones despachados de la operación asegurando el arribo oportuno al destino,verificando la aplicación de precintos de seguridad en los vagones que lo requieran.",
          "Verificar las condiciones de los vagones ferroviarios.",
          "Coordinar con el Operador Ferroviario las maniobras en patio de los vagones a entregar al almacén de destino",
          "Coordinar la entrega de los vagones con concentrado al depósito destino.",
          "Verificar que los vagones cumplan con la documentación legal requerida para su transporte.",
          "Elaborar reportes diarios de movimientos de vagones.",
          "Verificar el correcto manipuleo de materiales, equipos y suministros que impliquen riesgo al Medio Ambiente y/o a las personas, de acuerdo a procedimientos y normativas establecidas.",
          "Administrar y mantener actualizado el archivo de documentación propia del área.",
          "Comunicar oportunamente sobre cualquier contingencia que se presente en el área durante el desarrollo de sus funciones.",
          "Cubrir las operaciones de supervisión de despacho de concentrado desde Mina en ausencia del Supervisor de Almacén de Concentrado Mina."
        ]
      },
      {
        "title": "COORDINADOR SR DE TRAFICO INTERNACIONAL",
        "category": "Analista",
        "level": "Nivel 6",
        "blurb": "ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES",
        "speciality": "ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES",
        "experience_general": "6",
        "experience_position": "2",
        "experience_sector": "3",
        "carrera_afin": "INGENIERÍA INDUSTRIAL",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Coordinar las operaciones diarias de importación y exportación, dando seguimiento al avance de la Orden de Compra y confirmando el cierre de la misma al término de embarque de los parciales.",
          "Revisar documentación requerida por cada embarque de importación y exportación (liquidación de aduanas, Declaración Aduanera de Mercancías (DAM), Bill of Landing (BL) y Guias Aereas), gestionando el cierre de las mismas.",
          "Elaborar los costeos de importación y cotización de embarques (realizados y por realizar), dando seguimiento a las etapas de aprobación respectivas.",
          "Coordinar con los operadores logísticos en aduanas y transporte internacional respecto al status del tansito de los bienes requeridos.",
          "Administrar y coordinar los reclamos al Operador de Carga Internacional por discrepancias en el servicio y/o cobros de tarifas, en coordinacion con las compañias inspectoras y compañias de seguros para embarques siniestrados.",
          "Dar seguimiento a los regímenes de importación con valor provisional, temporales y suspensivos si lo hubiera.",
          "Apoyar con las coordinaciones de la certificación OEA y manejo del File del Operador BEAGLE"
        ]
      },
      {
        "title": "JEFE DE ALMACENES DE TRANSITO",
        "category": "Jefe",
        "level": "Nivel 10",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "10",
        "experience_position": "5",
        "experience_sector": "5",
        "carrera_afin": "ADMINISTRACIÓN",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Planificar, controlar y coordinar las labores de descarga, recepción, almacenamiento y despacho de materiales en el almacén de tránsito.",
          "Verificar, controlar y dar conformidad a las guías de materiales que lleguen al almacén de tránsito",
          "Controlar y verificar la cantidad y calidad de los materiales entregados por los proveedores y transportistas",
          "Coordinar el uso de equipos para las actividades propias del almacén de tránsito como la recepción, almacenamiento y despacho (camión, grúas y montacargas)",
          "Coordinar los inventarios cíclicos e inventarios programados por control interno, en los diferentes almacenes de tránsito",
          "Controlar e ingresar la información de recepción de materiales, insumos y equipos en el sistema ERP, manteniendo actualizada la información de inventarios.",
          "Coordinar y dirigir las actividades de despacho, manipuleo y recepción de materiales con el Operador Logístico (APM).",
          "Gestionar el soporte operativo requerido en la realización del inventario anual de los almacenes de MCP."
        ]
      },
      {
        "title": "SUPERINTENDENTE DE TRANSPORTE Y TRAFICO INTERNACIONAL",
        "category": "Superintendente",
        "level": "Nivel 15",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "15",
        "experience_position": "8",
        "experience_sector": "5",
        "carrera_afin": "ADMINISTRACIÓN\nECONOMÍA",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Dirigir los procesos de los almacenes de tránsito, importación, exportación y transporte de carga regular proporcionando soporte en las diferentes negociaciones de tarifas y condiciones de servicio con las diferentes entidades externas",
          "Coordinar y verificar la optimización del transporte y consolidación de carga; a fin de optimizar los costos y gastos de las operaciones",
          "Monitorear de manera continua el suministro de vagones de acuerdo a los requerimientos operativos",
          "Planificar las acciones preventivas y correctivas ante posibles contingencias en los procesos inspeccionados.",
          "Analizar la demanda y oferta respecto a la situación actual de las empresas navieras de mayor impacto económico y comercial",
          "Establecer controles para el ingreso correcto de la información  a los sistemas de control de los inventarios",
          "Establecer y coordinar un servicio adecuado y oportuno con el Operador Ferroviario para el transporte de los materiales y concentrado,",
          "Dirigir las actividades de despacho, manipuleo y recepción de materiales con el Operador Logístico (APM)."
        ]
      },
      {
        "title": "SUPERVISOR DE TRAFICO INTERNACIONAL",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES",
        "speciality": "ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES",
        "experience_general": "8",
        "experience_position": "4",
        "experience_sector": "5",
        "carrera_afin": "INGENIERÍA INDUSTRIAL",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Supervisar los procesos de Tráfico internacional, importación, exportación, desaduanaje y entrega en almacen de transito, controlando la disponibilidad / cumplimiento de documentación de sustento,  los costos de los procesos (tráfico y nacionalización) y KPI´s del área (transporte, aduanas, operadores de tráfico internacional y agentes de aduanas).",
          "Verificar los gastos asociados al proceso de importación, aprobando las facturas y proformas emitidas por los Agentes de Carga Internacional, Aduanas y por Gastos de importación.",
          "Participar en las negociaciones de tarifas y condiciones de servicio con operadores y brokers.",
          "Supervisar los incidentes y el cierre de reclamos de los operadores de tráfico internacional.",
          "Analizar el comportamiento de los embarques (semanal, mensual y consolidado anual), evaluando la oferta y demanda de empresas navieras en los puertos de origen de mayor impacto económico y comercial.",
          "Dar seguimiento al status de las Ordenes de Compra (para operaciones y proyectos), generando los reportes de gestión requeridos (liberación, entrega, otros), según la frecuencia solicitada.",
          "Establecer, proponer e implementar procedimientos, estándares e instrucciones de trabajo de tráfico internacional de acuerdo a las normas/necesidades vigentes.",
          "Coordinar con las áreas involucradas los aspectos requeridos por la certificación OEA, dando seguimiento a su implementación y cumplimiento."
        ]
      },
      {
        "title": "SUPERVISOR DE TRANSPORTE",
        "category": "Supervisor",
        "level": "Nivel 8",
        "blurb": "INGENIERÍA INDUSTRIAL",
        "speciality": "INGENIERÍA INDUSTRIAL",
        "experience_general": "8",
        "experience_position": "3",
        "experience_sector": "5",
        "carrera_afin": "ADMINISTRACIÓN",
        "idioma": "Inglés",
        "nivel": "Avanzado",
        "functions": [
          "Llevar a cabo acciones de reconocimiento y supervisión directa en ruta, coordinando la reparación de vías con el área de Proyectos si fuera requerido.",
          "Controlar y hacer seguimiento a las unidades que se encuentran en la operación de transporte a mina, movimientos internos y transporte fuera de mina, optimizando la capacidad de carga de los vehículos de transporte optimizando el costo por transporte.",
          "Realizar controles periódicos a transportistas, monitoreando el levantamiento de observaciones.",
          "Planificar y programar las unidades de transporte de acuerdo a los requerimientos de traslados de materiales y recursos de todas las áreas de la empresa.",
          "Determinar estrategias de traslado en coordinación con empresa de transporte.",
          "Revisar, analizar y validar los requerimiento de transporte especial (carga sobredimensionada o peligrosa) conjuntamente con las Empresas de Transporte."
        ]
      }
    ],
    "functions": [],
    "x": 580,
    "y": 460
  }
];

  const roleOptions = areaCatalog;
  const departments = areaCatalog;

  global.areaCatalog = areaCatalog;
  global.roleOptions = roleOptions;
  global.departments = departments;

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { areaCatalog, roleOptions, departments };
  }
})(typeof window !== 'undefined' ? window : global);
